### ISSUE TITLE
should evaluate truthiness like v-if/v-show

### ISSUE THREAD

**Issue by AlexandreBonaventure** [javisperez/vue-visible#1]
Hi, 
v-if and v-show evaluate condition by casting to Boolean whereas v-visible check if and only if `true`. IMO, This behaviour is misleading since you can't swap v-if/v-show with v-visible out of the box

**Comment by javisperez** [comment]
Hey, thank you for opening an issue! I think you're right and I should validate this better. I'll have a look when i get a chance and update the package as needed. Thank you for your feedback.

**Comment by javisperez** [comment]
This is done now, thank you for your feedback :)
