### ISSUE TITLE
Whole project downloaded via NPM - is it right?

### ISSUE THREAD

**Issue by kosiakMD** [javisperez/vue-visible#3]
Is it correctly the whole project to be downloaded if write `npm install ... --save`?

I think people need only `.js` file, no examples, no src, no webpack configs, just compiled and with `.map` version

**Comment by javisperez** [comment]
As the main file for the project is the `/dist/v-visible.js` file, no other file gets actually bundle when you do an import or so. Sometimes a src or example is useful for certain scenarios (like debuging or so), so if you're worried about the bundle's file size or performance, don't be :) only the final .js file is included
