### ISSUE TITLE
use Vuejs animations with v-visible

### ISSUE THREAD

**Issue by noudadrichem** [javisperez/vue-visible#5]
Hi, 

Are there any examples or is it even possible to use vuejs transitions/animations with v-visible? Not working for me at the moment..

**Comment by javisperez** [comment]
Sadly no, Vue doesnt allow custom directives to be `transitionable`, it just watches for certain directives like `show`, `hide`, `if`, `v-for`, etc. Cant add a custom one :-\

**Comment by Nisgrak** [comment]
@javisperez I think this change, see this jsfiddle https://stackoverflow.com/questions/64615373/how-to-make-transition-work-with-visibility-but-not-display

**Comment by javisperez** [comment]
Oh, nice! thanks for sharing @Nisgrak will take a look and implement accordingly. Thanks!
